# Generated by Django 5.2.17 on 2026-09-27 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120, verbose_name='نام مربی')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('specialty', models.CharField(blank=True, max_length=160, verbose_name='تخصص')),
                ('bio', models.TextField(blank=True, verbose_name='معرفی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='core.club', verbose_name='باشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سامانه')),
            ],
            options={
                'verbose_name': 'مربی',
                'verbose_name_plural': 'مربیان',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='نام کلاس')),
                ('starts_at', models.DateTimeField(verbose_name='شروع')),
                ('ends_at', models.DateTimeField(verbose_name='پایان')),
                ('capacity', models.PositiveSmallIntegerField(default=15, verbose_name='ظرفیت')),
                ('room', models.CharField(blank=True, max_length=80, verbose_name='سالن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی\u200cشده'), ('cancelled', 'لغوشده'), ('completed', 'برگزارشده')], default='scheduled', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fitness_classes', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_classes', to='core.club', verbose_name='باشگاه')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='trainers.trainer', verbose_name='مربی')),
            ],
            options={
                'verbose_name': 'سانس کلاس',
                'verbose_name_plural': 'سانس\u200cهای کلاس',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'رزرو قطعی'), ('waitlist', 'فهرست انتظار'), ('cancelled', 'لغوشده'), ('attended', 'حاضر')], default='booked', max_length=12, verbose_name='وضعیت رزرو')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان رزرو')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حضور')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to='core.club', verbose_name='باشگاه')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_bookings', to='members.member', verbose_name='عضو')),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trainers.fitnessclass', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'رزرو کلاس',
                'verbose_name_plural': 'رزروهای کلاس',
                'ordering': ['booked_at'],
                'constraints': [models.UniqueConstraint(fields=('fitness_class', 'member'), name='uniq_member_per_class')],
            },
        ),
        migrations.AddConstraint(
            model_name='trainer',
            constraint=models.UniqueConstraint(condition=models.Q(('mobile', ''), _negated=True), fields=('club', 'mobile'), name='uniq_trainer_mobile_per_club'),
        ),
        migrations.AddIndex(
            model_name='fitnessclass',
            index=models.Index(fields=['club', 'starts_at'], name='trainers_fi_club_id_6dcced_idx'),
        ),
    ]
