# Generated by Django 5.2.17 on 2026-09-27 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, verbose_name='کد کالا')),
                ('name', models.CharField(max_length=140, verbose_name='نام کالا')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='دسته')),
                ('unit', models.CharField(default='عدد', max_length=30, verbose_name='واحد')),
                ('cost_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت خرید (ریال)')),
                ('sale_price', models.PositiveBigIntegerField(verbose_name='قیمت فروش (ریال)')),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='موجودی')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='حداقل موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_products', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'کالای فروشگاه',
                'verbose_name_plural': 'کالاهای فروشگاه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'افزایش'), ('out', 'کاهش')], max_length=3, verbose_name='نوع')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('reason', models.CharField(blank=True, max_length=180, verbose_name='شرح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='core.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='store.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'گردش موجودی',
                'verbose_name_plural': 'گردش موجودی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد (ریال)')),
                ('sold_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان فروش')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_sales', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_sales', to='core.club')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_sales', to='members.member', verbose_name='عضو')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='store.product', verbose_name='کالا')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فروش فروشگاه',
                'verbose_name_plural': 'فروش\u200cهای فروشگاه',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['club', 'stock_quantity'], name='store_produ_club_id_2fb7c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('club', 'sku'), name='uniq_store_sku_per_club'),
        ),
        migrations.AddIndex(
            model_name='storesale',
            index=models.Index(fields=['club', 'sold_at'], name='store_store_club_id_5d1f40_idx'),
        ),
    ]
