# Generated by Django 5.2.17 on 2026-09-27 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='نام باشگاه')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد باشگاه')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='شناسه یکتا')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/', verbose_name='لوگو')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'معلق'), ('archived', 'بایگانی')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'باشگاه',
                'verbose_name_plural': 'باشگاه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=100, verbose_name='نام ماژول')),
                ('icon', models.CharField(default='◈', max_length=50, verbose_name='آیکن')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('implemented', models.BooleanField(default=False, verbose_name='پیاده\u200cسازی شده')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'ماژول سیستم',
                'verbose_name_plural': 'ماژول\u200cهای سیستم',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('login', 'ورود'), ('switch_club', 'تغییر باشگاه')], max_length=30, verbose_name='عملیات')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='مدل')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='شناسه شیء')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'لاگ عملیات',
                'verbose_name_plural': 'لاگ عملیات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام شعبه')),
                ('code', models.CharField(max_length=30, verbose_name='کد شعبه')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبه\u200cها',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('club', 'code'), name='uniq_branch_code_per_club')],
            },
        ),
        migrations.CreateModel(
            name='ClubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='فعال برای این باشگاه')),
                ('settings_json', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات ماژول')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.club', verbose_name='باشگاه')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_settings', to='core.systemmodule', verbose_name='ماژول')),
            ],
            options={
                'verbose_name': 'فعال\u200cسازی ماژول باشگاه',
                'verbose_name_plural': 'فعال\u200cسازی ماژول\u200cهای باشگاه',
                'constraints': [models.UniqueConstraint(fields=('club', 'module'), name='uniq_module_per_club')],
            },
        ),
    ]
