# Generated by Django 5.2.17 on 2026-09-27 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام پلن')),
                ('code', models.CharField(max_length=30, verbose_name='کد پلن')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت (روز)')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (ریال)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('max_checkins', models.PositiveIntegerField(blank=True, help_text='خالی یعنی نامحدود', null=True, verbose_name='حداکثر ورود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'پلن عضویت',
                'verbose_name_plural': 'پلن\u200cهای عضویت',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=40, verbose_name='شماره قرارداد')),
                ('start_date', models.DateField(verbose_name='شروع')),
                ('end_date', models.DateField(verbose_name='پایان')),
                ('agreed_price', models.PositiveBigIntegerField(verbose_name='مبلغ قرارداد (ریال)')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف (ریال)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('expired', 'پایان\u200cیافته'), ('cancelled', 'لغوشده')], default='active', max_length=12, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_contracts', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_contracts', to='core.club', verbose_name='باشگاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='members.member', verbose_name='عضو')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='membership.membershipplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'قرارداد عضویت',
                'verbose_name_plural': 'قراردادهای عضویت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (ریال)')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ پرداخت')),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت\u200cخوان'), ('transfer', 'کارت\u200cبه\u200cکارت'), ('online', 'آنلاین'), ('other', 'سایر')], default='cash', max_length=12, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('paid', 'پرداخت\u200cشده'), ('pending', 'در انتظار'), ('refunded', 'مستردشده')], default='paid', max_length=12, verbose_name='وضعیت')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_payments', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to='core.club', verbose_name='باشگاه')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='membership.membershipcontract', verbose_name='قرارداد')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member', verbose_name='عضو')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(fields=('club', 'code'), name='uniq_plan_code_per_club'),
        ),
        migrations.AddIndex(
            model_name='membershipcontract',
            index=models.Index(fields=['club', 'member', 'status'], name='membership__club_id_a4505b_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipcontract',
            constraint=models.UniqueConstraint(fields=('club', 'contract_code'), name='uniq_contract_code_per_club'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['club', 'paid_on'], name='membership__club_id_a5e412_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['club', 'member'], name='membership__club_id_7bdecb_idx'),
        ),
    ]
