# Generated by Django 5.2.17 on 2026-09-27 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام صندوق/حساب')),
                ('opening_balance', models.BigIntegerField(default=0, verbose_name='مانده آغازین (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_accounts', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'صندوق یا حساب',
                'verbose_name_plural': 'صندوق\u200cها و حساب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('entry_type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=8, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_categories', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'دسته مالی',
                'verbose_name_plural': 'دسته\u200cهای مالی',
                'ordering': ['entry_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=8, verbose_name='نوع')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (ریال)')),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ')),
                ('description', models.CharField(max_length=220, verbose_name='شرح')),
                ('source', models.CharField(choices=[('manual', 'ثبت دستی'), ('membership_payment', 'پرداخت عضویت'), ('store_sale', 'فروشگاه'), ('cafe_order', 'کافی\u200cشاپ')], default='manual', max_length=24, verbose_name='منبع')),
                ('source_id', models.CharField(blank=True, max_length=64, verbose_name='شناسه مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.cashaccount', verbose_name='صندوق/حساب')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='core.branch', verbose_name='شعبه')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.financecategory', verbose_name='دسته')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='core.club', verbose_name='باشگاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سند مالی',
                'verbose_name_plural': 'سندهای مالی',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='uniq_cash_account_per_club'),
        ),
        migrations.AddConstraint(
            model_name='financecategory',
            constraint=models.UniqueConstraint(fields=('club', 'name', 'entry_type'), name='uniq_finance_category_per_club_type'),
        ),
        migrations.AddIndex(
            model_name='financeentry',
            index=models.Index(fields=['club', 'occurred_on', 'entry_type'], name='finance_fin_club_id_747c7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id', ''), _negated=True), fields=('club', 'source', 'source_id'), name='uniq_finance_source_record'),
        ),
    ]
