# Generated by Django 5.2.17 on 2026-09-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='نام تجهیز')),
                ('asset_code', models.CharField(max_length=60, verbose_name='کد اموال')),
                ('location', models.CharField(blank=True, max_length=140, verbose_name='محل استقرار')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('service', 'نیازمند سرویس'), ('repair', 'خراب'), ('retired', 'خارج از سرویس')], default='active', max_length=16, verbose_name='وضعیت')),
                ('purchased_on', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='شرح سرویس/خرابی')),
                ('reported_on', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='موعد')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام')),
                ('cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه (ریال)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-reported_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('club', 'asset_code'), name='uniq_equipment_code_club'),
        ),
    ]
