# Generated by Django 5.2.17 on 2026-09-29 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان نقش')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='توضیح')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.club', verbose_name='باشگاه')),
                ('permissions', models.ManyToManyField(blank=True, related_name='club_roles', to='auth.permission', verbose_name='دسترسی\u200cها')),
            ],
            options={
                'verbose_name': 'نقش باشگاه',
                'verbose_name_plural': 'نقش\u200cهای باشگاه',
                'ordering': ['name'],
                'permissions': [('view_dashboard', 'مشاهده: داشبورد'), ('view_members', 'مشاهده: اعضا'), ('view_membership', 'مشاهده: عضویت و قراردادها'), ('view_attendance', 'مشاهده: حضور و غیاب'), ('view_access', 'مشاهده: کنترل ورود'), ('view_training', 'مشاهده: مربیان و کلاس\u200cها'), ('view_store', 'مشاهده: فروشگاه'), ('view_cafe', 'مشاهده: کافی\u200cشاپ'), ('view_workouts', 'مشاهده: تمرین و ارزیابی'), ('view_finance', 'مشاهده: مالی و صندوق'), ('view_crm', 'مشاهده: CRM و پیگیری'), ('view_reports', 'مشاهده: گزارش\u200cها'), ('view_api', 'مشاهده: یکپارچه\u200cسازی API'), ('view_mobile', 'مشاهده: پرتال موبایل'), ('view_equipment', 'مشاهده: تجهیزات'), ('view_users', 'مشاهده: کاربران و نقش\u200cها'), ('add_members', 'ثبت: اعضا'), ('add_membership', 'ثبت: عضویت و قراردادها'), ('add_attendance', 'ثبت: حضور و غیاب'), ('add_access', 'ثبت: کنترل ورود'), ('add_training', 'ثبت: مربیان و کلاس\u200cها'), ('add_store', 'ثبت: فروشگاه'), ('add_cafe', 'ثبت: کافی\u200cشاپ'), ('add_workouts', 'ثبت: تمرین و ارزیابی'), ('add_finance', 'ثبت: مالی و صندوق'), ('add_crm', 'ثبت: CRM و پیگیری'), ('add_api', 'ثبت: یکپارچه\u200cسازی API'), ('add_equipment', 'ثبت: تجهیزات'), ('add_users', 'ثبت: کاربران و نقش\u200cها'), ('change_members', 'ویرایش: اعضا'), ('change_membership', 'ویرایش: عضویت و قراردادها'), ('change_attendance', 'ویرایش: حضور و غیاب'), ('change_access', 'ویرایش: کنترل ورود'), ('change_training', 'ویرایش: مربیان و کلاس\u200cها'), ('change_store', 'ویرایش: فروشگاه'), ('change_cafe', 'ویرایش: کافی\u200cشاپ'), ('change_workouts', 'ویرایش: تمرین و ارزیابی'), ('change_finance', 'ویرایش: مالی و صندوق'), ('change_crm', 'ویرایش: CRM و پیگیری'), ('change_api', 'ویرایش: یکپارچه\u200cسازی API'), ('change_equipment', 'ویرایش: تجهیزات'), ('change_users', 'ویرایش: کاربران و نقش\u200cها'), ('delete_members', 'حذف: اعضا'), ('delete_membership', 'حذف: عضویت و قراردادها'), ('delete_attendance', 'حذف: حضور و غیاب'), ('delete_access', 'حذف: کنترل ورود'), ('delete_training', 'حذف: مربیان و کلاس\u200cها'), ('delete_store', 'حذف: فروشگاه'), ('delete_cafe', 'حذف: کافی\u200cشاپ'), ('delete_workouts', 'حذف: تمرین و ارزیابی'), ('delete_finance', 'حذف: مالی و صندوق'), ('delete_crm', 'حذف: CRM و پیگیری'), ('delete_api', 'حذف: یکپارچه\u200cسازی API'), ('delete_equipment', 'حذف: تجهیزات'), ('delete_users', 'حذف: کاربران و نقش\u200cها')],
            },
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='club_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.clubrole', verbose_name='سطح دسترسی'),
        ),
        migrations.AddConstraint(
            model_name='clubrole',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='uniq_role_name_per_club'),
        ),
    ]
