# Generated by Django 5.2.17 on 2026-09-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clubrole_clubmembership_club_role_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='direct_permissions',
            field=models.ManyToManyField(blank=True, related_name='direct_club_memberships', to='auth.permission', verbose_name='دسترسی\u200cهای اختصاصی'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='webapp_enabled',
            field=models.BooleanField(default=True, verbose_name='دسترسی به Web App'),
        ),
    ]
