# Generated by Django 5.2.17 on 2026-09-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='شروع مجاز ورود')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='پایان مجاز ورود')),
                ('allowed_weekdays', models.JSONField(blank=True, default=list, help_text='۰ شنبه، ۶ جمعه؛ خالی یعنی همه روزها', verbose_name='روزهای مجاز هفته')),
                ('enforce_hours', models.BooleanField(default=False, verbose_name='اعمال ساعت مجاز')),
                ('enforce_days', models.BooleanField(default=False, verbose_name='اعمال روزهای مجاز')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy', to='core.club', verbose_name='باشگاه')),
            ],
        ),
        migrations.CreateModel(
            name='AccessCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('qr', 'QR'), ('rfid', 'RFID'), ('card', 'کارت'), ('pin', 'کد دستی')], default='qr', max_length=8, verbose_name='نوع شناسه')),
                ('token', models.CharField(max_length=160, verbose_name='کد/توکن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین استفاده')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_credentials', to='core.club', verbose_name='باشگاه')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_credentials', to='members.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'شناسه ورود',
                'verbose_name_plural': 'شناسه\u200cهای ورود',
                'ordering': ['member__last_name', 'member__first_name'],
                'indexes': [models.Index(fields=['club', 'token', 'is_active'], name='access_cont_club_id_378810_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'token'), name='uniq_access_token_per_club')],
            },
        ),
        migrations.CreateModel(
            name='GuestPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120, verbose_name='نام مهمان')),
                ('guest_mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل مهمان')),
                ('pass_code', models.CharField(max_length=40, verbose_name='کد مهمان')),
                ('valid_on', models.DateField(verbose_name='تاریخ اعتبار')),
                ('status', models.CharField(choices=[('issued', 'صادرشده'), ('used', 'استفاده\u200cشده'), ('cancelled', 'لغوشده')], default='issued', max_length=12, verbose_name='وضعیت')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='صدور')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_passes', to='core.club', verbose_name='باشگاه')),
                ('host_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_passes', to='members.member', verbose_name='عضو میزبان')),
            ],
            options={
                'verbose_name': 'مجوز مهمان',
                'verbose_name_plural': 'مجوزهای مهمان',
                'ordering': ['-valid_on', '-id'],
                'constraints': [models.UniqueConstraint(fields=('club', 'pass_code'), name='uniq_guest_pass_per_club')],
            },
        ),
    ]
