# Generated by Django 5.2.17 on 2026-09-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(max_length=20, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='منبع آشنایی')),
                ('stage', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('trial', 'جلسه آزمایشی'), ('won', 'ثبت\u200cنام شد'), ('lost', 'از دست رفته')], default='new', max_length=16, verbose_name='مرحله')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.club')),
                ('converted_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'تماس'), ('meeting', 'جلسه'), ('message', 'پیام'), ('note', 'یادداشت')], default='call', max_length=12, verbose_name='نوع پیگیری')),
                ('summary', models.CharField(max_length=240, verbose_name='شرح')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پیگیری')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انجام\u200cشده در')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'پیامک'), ('email', 'ایمیل'), ('push', 'اعلان')], default='sms', max_length=8, verbose_name='کانال')),
                ('recipient', models.CharField(max_length=160, verbose_name='گیرنده')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان\u200cبندی')),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق'), ('cancelled', 'لغوشده')], default='queued', max_length=12, verbose_name='وضعیت')),
                ('provider_ref', models.CharField(blank=True, max_length=160, verbose_name='شناسه سرویس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['club', 'stage'], name='crm_lead_club_id_64f4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['club', 'mobile'], name='crm_lead_club_id_3a45c0_idx'),
        ),
    ]
