# Generated by Django 5.2.17 on 2026-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagequeue',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='messagequeue',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('club', 'dedupe_key'), name='uniq_message_dedupe_per_club'),
        ),
    ]
