# Generated by Django 5.2.17 on 2026-09-27 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='نام حرکت')),
                ('muscle_group', models.CharField(blank=True, max_length=100, verbose_name='گروه عضلانی')),
                ('equipment', models.CharField(blank=True, max_length=100, verbose_name='وسیله')),
                ('instructions', models.TextField(blank=True, verbose_name='نحوه اجرا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'حرکت تمرینی',
                'verbose_name_plural': 'بانک حرکات',
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='نام برنامه')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20, verbose_name='سطح')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='core.club', verbose_name='باشگاه')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans', to='trainers.trainer', verbose_name='مربی')),
            ],
            options={
                'verbose_name': 'برنامه تمرینی',
                'verbose_name_plural': 'برنامه\u200cهای تمرینی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='شروع برنامه')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='پایان برنامه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='core.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_assignments', to='members.member', verbose_name='عضو')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workouts.workoutplan', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'انتساب برنامه',
                'verbose_name_plural': 'برنامه\u200cهای اعضا',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(default=1, verbose_name='روز برنامه')),
                ('sets', models.PositiveSmallIntegerField(default=3, verbose_name='ست')),
                ('repetitions', models.CharField(default='10', max_length=40, verbose_name='تکرار/مدت')),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60, verbose_name='استراحت (ثانیه)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('notes', models.CharField(blank=True, max_length=160, verbose_name='یادداشت')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='workouts.exercise', verbose_name='حرکت')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workouts.workoutplan', verbose_name='برنامه')),
            ],
            options={
                'verbose_name': 'حرکت در برنامه',
                'verbose_name_plural': 'حرکات برنامه',
                'ordering': ['day_number', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BodyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ ارزیابی')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='قد (سانتی\u200cمتر)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='وزن (کیلوگرم)')),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='درصد چربی')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='دور کمر (سانتی\u200cمتر)')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='دور سینه (سانتی\u200cمتر)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_assessments', to='core.branch')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_assessments', to='core.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_assessments', to='members.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'ارزیابی بدنی',
                'verbose_name_plural': 'ارزیابی\u200cهای بدنی',
                'ordering': ['-measured_on', '-id'],
                'indexes': [models.Index(fields=['club', 'member', 'measured_on'], name='workouts_bo_club_id_e4db66_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='uniq_exercise_name_per_club'),
        ),
        migrations.AddIndex(
            model_name='workoutassignment',
            index=models.Index(fields=['club', 'member', 'is_active'], name='workouts_wo_club_id_cc49d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='planexercise',
            constraint=models.UniqueConstraint(fields=('plan', 'day_number', 'exercise'), name='uniq_exercise_per_plan_day'),
        ),
    ]
