# Generated by Django 5.2.17 on 2026-09-27 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=30, verbose_name='کد عضویت')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی')),
                ('mobile', models.CharField(max_length=20, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, verbose_name='جنسیت')),
                ('emergency_name', models.CharField(blank=True, max_length=120, verbose_name='نام تماس اضطراری')),
                ('emergency_mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل اضطراری')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('suspended', 'معلق'), ('blocked', 'مسدود')], default='active', max_length=20, verbose_name='وضعیت')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='عکس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضا',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['club', 'mobile'], name='members_mem_club_id_697a64_idx'), models.Index(fields=['club', 'national_id'], name='members_mem_club_id_5ef14d_idx'), models.Index(fields=['club', 'status'], name='members_mem_club_id_6e1393_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'member_code'), name='uniq_member_code_per_club')],
            },
        ),
    ]
