# Generated by Django 5.2.17 on 2026-09-27 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='زمان ورود')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('status', models.CharField(choices=[('open', 'داخل باشگاه'), ('closed', 'خروج ثبت\u200cشده'), ('denied', 'ورود غیرمجاز')], default='open', max_length=10, verbose_name='وضعیت')),
                ('denial_reason', models.CharField(blank=True, max_length=200, verbose_name='علت عدم پذیرش')),
                ('source', models.CharField(default='reception', max_length=30, verbose_name='منبع ثبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.club', verbose_name='باشگاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='members.member', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'تردد عضو',
                'verbose_name_plural': 'تردد اعضا',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['club', 'check_in'], name='attendance__club_id_8dc81e_idx'), models.Index(fields=['club', 'status'], name='attendance__club_id_a1be65_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('club', 'member'), name='uniq_open_visit_per_member_club')],
            },
        ),
    ]
