# Generated by Django 5.2.17 on 2026-09-27 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام محصول')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='دسته')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (ریال)')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود در منو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_menu', to='core.club', verbose_name='باشگاه')),
            ],
            options={
                'verbose_name': 'محصول کافی\u200cشاپ',
                'verbose_name_plural': 'منوی کافی\u200cشاپ',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CafeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد (ریال)')),
                ('status', models.CharField(choices=[('open', 'در حال آماده\u200cسازی'), ('ready', 'آماده'), ('served', 'تحویل\u200cشده'), ('cancelled', 'لغوشده')], default='open', max_length=12, verbose_name='وضعیت')),
                ('notes', models.CharField(blank=True, max_length=180, verbose_name='یادداشت')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان سفارش')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cafe_orders', to='core.branch', verbose_name='شعبه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_orders', to='core.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_orders', to='members.member', verbose_name='عضو')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cafe.menuitem', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش کافی\u200cشاپ',
                'verbose_name_plural': 'سفارش\u200cهای کافی\u200cشاپ',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='uniq_cafe_item_per_club'),
        ),
        migrations.AddIndex(
            model_name='cafeorder',
            index=models.Index(fields=['club', 'ordered_at'], name='cafe_cafeor_club_id_da02c0_idx'),
        ),
    ]
